#ifndef FOLLOW_SETS_H
#define FOLLOW_SETS_H

#include "tokens.h"
#include "set.h"

void initializeFollowSets();

node FOLLOW_SET_START;
node FOLLOW_SET_IDENT_LIST_TYPE;
node FOLLOW_SET_IDENT_LIST;
node FOLLOW_SET_TYPE;
node FOLLOW_SET_SIMPLE_TYPE;
node FOLLOW_SET_COMP_STMT;
node FOLLOW_SET_STMT_LIST;
node FOLLOW_SET_STATEMENT;
node FOLLOW_SET_ASSIGN_STMT;
node FOLLOW_SET_ASSIGN_STMT_2;
node FOLLOW_SET_IF_STMT;
node FOLLOW_SET_WHILE_STMT;
node FOLLOW_SET_FOR_STMT;
node FOLLOW_SET_TO_PART;
node FOLLOW_SET_EXPR;
node FOLLOW_SET_EXPR_LIST;
node FOLLOW_SET_SIMPLE_EXPR;
node FOLLOW_SET_TERM;
node FOLLOW_SET_FACTOR;
node FOLLOW_SET_REL_OP;
node FOLLOW_SET_ADD_OP;
node FOLLOW_SET_MUL_OP;

#endif
